### ISSUE TITLE
Setup the Scribe-Server project

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Server#1]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Server/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Server's [Code of Conduct](https://github.com/scribe-org/Scribe-Server/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to track the initial setup for the Scribe-Server project.

Details on the Definition of Done can be more clearly refined in the discussion for the issue. Tentatively, the DoD could be the setup for a minimal server.

### Contribution

Will take this on :sunglasses:

**Comment by wkyoshida** [comment]
Thinking that with #3 it should be progress enough to be able to close this issue.

**Comment by andrewtavis** [comment]
#3's merged, so closing this @wkyoshida :) Let me know if we need to reopen though. Stoked!
