### ISSUE TITLE
Design the pre-rendered data count image

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Server#10]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Server/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Server's [Code of Conduct](https://github.com/scribe-org/Scribe-Server/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, data count stats are provided via a Markdown table in Scribe `README`s ([example](https://github.com/scribe-org/Scribe-Server#supported-languages-))

Once Scribe-Server is set up to periodically perform the ETL process for Scribe data, updating the data count stats will become troublesome. One idea is to have Scribe-Server pre-render an image with the data count stats and then serve the image to be referenced where needed.

This issue is for the design of the pre-rendered data count image.

### Contribution

@andrewtavis would you be able to create a design on Figma for how we would like this to look?

**Comment by andrewtavis** [comment]
Sure thing, @wkyoshida! Big thing to note on this is that we should likely use `#646464` for the color hex (Python grey that I use for logos and such). Reason for this is that we won't be able to rely on GitHub color mode switching the cells from black to white for dark mode. We could do two different versions and use their readme color mode prefers syntax, but then I've found that to be a bit buggy.

I'll get to this soonish so we can close this up :)

**Comment by andrewtavis** [comment]
Hadn't thought as far into it, but yes maybe something a bit more interactive would make sense. And ya having the background be transparent was generally the plan 😊

**Comment by andrewtavis** [comment]
Just added the annotations in as well :) Let me know if anything else is needed for this, @wkyoshida!

**Comment by andrewtavis** [comment]
Closing this up given the presentation of the new designs [mentioned above](https://github.com/scribe-org/Scribe-Server/issues/10#issuecomment-1963863851) at the last dev sync :)
