### ISSUE TITLE
Add Toolforge to the 'Wikimedia Communities' section

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Server#11]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Server/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Server's [Code of Conduct](https://github.com/scribe-org/Scribe-Server/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is for adding [Toolforge](https://wikitech.wikimedia.org/wiki/Portal:Toolforge/About_Toolforge) as another community under the [`Wikimedia Communities`](https://github.com/scribe-org/Scribe-Server#wikimedia-communities) section of the Scribe-Server `README.md`. This likely includes adding the Toolforge logo in the Organization repo as well [here](https://github.com/scribe-org/Organization/tree/main/resources/images/logos)

NOTE:
- Toolforge is the platform where Scribe is hosting the Scribe-Server project

**Comment by andrewtavis** [comment]
5bbfa6c closes this up, @wkyoshida! 😊 Thanks for thinking of this! 🔨
