### ISSUE TITLE
Docker tooling for local development

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Server#7]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Server/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Server's [Code of Conduct](https://github.com/scribe-org/Scribe-Server/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is for configuring Docker tooling for local development. Most importantly, this is for running a local instance of MariaDB, which is the DB flavor used in the Toolforge platform where Scribe-Server is hosted.

Goals here are primarily to:
- Configure a MariaDB `Dockerfile` for local development
- Configure a `docker-compose.yaml` as well for spinning up the local dev environment

Setting this up is to facilitate development around Scribe-Server's persistence layer

**Comment by henrikth93** [comment]
I am interested in this!

**Comment by wkyoshida** [comment]
Awesome, @henrikth93!! :rocket: 

This should be fairly straightforward if familiar with Docker. Do let me know though if you need any additional pointers or information on this!

And actually though - I am  thinking that a `Dockerfile` might not be needed even for this really.. cause the `docker-compose.yaml` could simply specify to use the official [`mariadb`](https://hub.docker.com/_/mariadb) image. 

Other things related here could also include (though not required, but feel free to look into if interested):
- Adding a [`Makefile`](https://github.com/scribe-org/Scribe-Server/blob/main/Makefile) target, such as `make local-db` perhaps, to spin up the local DB instance

---

I've been fairly solo here with Scribe-Server so far :laughing:, so let me know if there's anything that needs clarification!

**Comment by wkyoshida** [comment]
Thanks, @henrikth93! 🙏
